site_name: Mkdocs Test
copyright: "&copy; 2022 mebiusbox"
repo_url: https://github.com/mebiusbox/MkDocsTest
repo_name: mebiusbox/MkDocsTest
theme:
  name: material
  feature:
    - content.code.annotate
    - tabs: true
  icon:
    repo: fontawesome/brands/github
    # repo: fontawesome/brands/gitlab
  custom_dir: overrides
nav:
  - Home: index.md
  - extensions:
    - math.md
    - admonition.md
    - footnotes.md
    - fontawesome.md
    - deflist.md
    - emoji.md
    - smartsymbols.md
    - keys.md
    - codehilite.md
    - mkdocs.md

plugins:
  search:
    lang: 'ja'

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mebiusbox2
      name: mebiusbox2 on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/mebiusbox/MkDocsTest
  generator: false

extra_javascript: 
    - "js/extra.js"
    - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML"
  # - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  
extra_css:
  - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
  - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
  - "css/extra.css"
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

markdown_extensions:
  - mdx_math
  - admonition
  - footnotes
  - fontawesome_markdown
  - def_list
  - pymdownx.smartsymbols
  - pymdownx.keys
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: monokai
      linenums: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      # emoji_generator: !!python/name:pymdownx.emoji.to_alt
